### ISSUE TITLE
Can I use your library to find the nose position in my point cloud data?

### ISSUE THREAD

**Issue by Ostnie** [fengju514/Face-Pose-Net#10]
I am  doing some research in 3d face point cloud,I have only a little experience,Now I have a problem that I can't find the nose position in my point cloud data,I see maybe your library can help me but I don't find the right program,could you help me? or tell me wether it can do this,many thanks!

**Comment by TalHassner** [comment]
@Ostnie, I'm not entirely sure what you are asking for. 

You can use FacePoseNet to obtain a very accurate estimate of the position of the nose in an input image of a face (the pixel coordinates of the nose), however, FacePoseNet won't help you find the position of a 3D nose in an unaligned 3D point-cloud.

**Comment by iacopomasi** [comment]
Hi @Ostnie ,
I think this paper can be very helpful though it depends on how much your data points are noisy.

> A. Mian, M. Bennamoun and R. Owens, "An Efficient Multimodal 2D-3D Hybrid Approach to Automatic Face Recognition," in IEEE Transactions on Pattern Analysis and Machine Intelligence, vol. 29, no. 11, pp. 1927-1943, Nov. 2007.
doi: 10.1109/TPAMI.2007.1105


See in particular **Sec. 3 and Fig. 3.**

I hope this helps.
-iacopo

**Comment by Ostnie** [comment]
Hi @iacopomasi ，thank you very much for your help, let me have a try
