### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by pavibalaji** [fengju514/Face-Pose-Net#13]
Hello,

I am facing the below error,

/programs/Face-Pose-Net-master/face_renderer/ThreeD_Model.py", line 65, in createMask
    contours, hierarchy = cv2.findContours(eyemask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)

Any help? Thanks

**Comment by iacopomasi** [comment]
@pavibalaji ,
Check my other response in [here](https://github.com/iacopomasi/face_specific_augm/issues/17). You need to use OpenCV2 for now.

I hope this helps.
