### ISSUE TITLE
Posevector Format and plotting

### ISSUE THREAD

**Issue by ssundar6087** [fengju514/Face-Pose-Net#14]
Hello,

I have a couple of quick questions reg the pose vector generated. Is my understanding of the code correct?

1) Pose vector is in the variable predRts

2) The vector has 3 Rotational and 3 translational parameters

3) The Rotation parameters are in radian and stored in the order Pitch (PredRts[0][0]) Yaw (PredRts[0][1]) and Roll (PredRts[0][2]) and the translation parameters are the remaining three in mm

4) Is there a utility function to plot the pose vectors generated on the input image (Superimpose the three axes on the image). If not, is there a utility script that exists somewhere which I can leverage? I want to visualize the results to check my understanding of the code. 

Thanks

**Comment by fengju514** [comment]
The first three are correct!

For question 4. you can refer to the following link:
https://docs.opencv.org/3.1.0/d7/d53/tutorial_py_pose.html

**Comment by ssundar6087** [comment]
Thanks for confirming!
