### ISSUE TITLE
Error when I use Face-Pose-Net,pls help me!

### ISSUE THREAD

**Issue by summerice021** [fengju514/Face-Pose-Net#15]
Dear Developer:
 
Hello,I have download your python open source project :
Face-Pose-Net   https://github.com/fengju514/Face-Pose-Net
 
Why it pop up this bug:

 
ModuleNotFoundError: No module named 'camera_calibration'
 
I have 1G of picture about human face,I need to get 6 DOF of their rotation,now I have to do the job hand by hand.I sincerely need your project to automatically do my job,please help me!
 
Xia Zhenghan
2018.2.26

**Comment by fengju514** [comment]
`camera_calibration.py` should be in the folder `face-renderer`
I think you didn't download the face-renderer properly.
Please use the command `git clone --recursive https://github.com/fengju514/Face-Pose-Net`
to get all files properly
