### ISSUE TITLE
how to convert the result to angle ?

### ISSUE THREAD

**Issue by translatorgoogle** [fengju514/Face-Pose-Net#16]
the results printed by your code is:
Model restored.
Predicted pose for:  subject10_a
[  8.27930197e-02   1.95288494e-01   1.03690195e+00  -1.98086071e+01
   8.39025688e+00   3.26982227e+03]
Predicted pose for:  subject10_a_flip
[  1.37187794e-01  -1.48106769e-01  -1.06753802e+00   2.50120773e+01
   4.28642845e+00   3.29182764e+03]

then how to convert the results to raw,roll,and pitch angle?
much thx：）

**Comment by fengju514** [comment]
The first three elements as shown in the results are already pitch, yaw, and roll angle (in the unit of radian).

**Comment by translatorgoogle** [comment]
I want you to help me confirm the order of pitch, yaw and roll, which is the first, which the second and which the third? thx:)

**Comment by fengju514** [comment]
The order is pitch, yaw, and roll

**Comment by fuhuacy** [comment]
Model restored.
Predicted pose for:  subject10_a
Predicted pose for:  subject10_a_flip
Predicted pose for:  subject3_a
Predicted pose for:  subject3_a_flip
Predicted pose for:  subject6_a
Predicted pose for:  subject6_a_flip
Predicted pose for:  subject8_a
Predicted pose for:  subject8_a_flip
Predicted pose for:  subject4_a
Predicted pose for:  subject4_a_flip
Predicted pose for:  subject7_a
Predicted pose for:  subject7_a_flip
Predicted pose for:  subject9_a
Predicted pose for:  subject9_a_flip
Predicted pose for:  subject5_a
Predicted pose for:  subject5_a_flip
Predicted pose for:  subject1_a
Predicted pose for:  subject1_a_flip
Predicted pose for:  subject2_a
Predicted pose for:  subject2_a_flip
> Yaw value mean:  6.99341473215
> Looking at file: ./tmp/subject10_a.jpg with model3D_aug_-00_00_10.mat
> Using pose model in model3D_aug_-00_00_10.mat
> Query image shape: (227, 227, 3)
> Looking at file: ./tmp/subject10_a.jpg with model3D_aug_-22_00_10.mat
> Using pose model in model3D_aug_-22_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject10_a.jpg with model3D_aug_-40_00_10.mat
> Using pose model in model3D_aug_-40_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject10_a.jpg with model3D_aug_-55_00_10.mat
> Using pose model in model3D_aug_-55_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject10_a.jpg with model3D_aug_-75_00_10.mat
> Using pose model in model3D_aug_-75_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Yaw value mean:  23.9717266464
> Looking at file: ./tmp/subject3_a.jpg with model3D_aug_-40_00_10.mat
> Using pose model in model3D_aug_-40_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject3_a.jpg with model3D_aug_-55_00_10.mat
> Using pose model in model3D_aug_-55_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject3_a.jpg with model3D_aug_-75_00_10.mat
> Using pose model in model3D_aug_-75_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Yaw value mean:  25.6346889259
> Looking at file: ./tmp/subject6_a.jpg with model3D_aug_-40_00_10.mat
> Using pose model in model3D_aug_-40_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject6_a.jpg with model3D_aug_-55_00_10.mat
> Using pose model in model3D_aug_-55_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject6_a.jpg with model3D_aug_-75_00_10.mat
> Using pose model in model3D_aug_-75_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Yaw value mean:  -29.4401957865
> Looking at file: ./tmp/subject8_a.jpg with model3D_aug_-40_00_10.mat
> Using pose model in model3D_aug_-40_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject8_a.jpg with model3D_aug_-55_00_10.mat
> Using pose model in model3D_aug_-55_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject8_a.jpg with model3D_aug_-75_00_10.mat
> Using pose model in model3D_aug_-75_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Yaw value mean:  -26.8160232163
> Looking at file: ./tmp/subject4_a.jpg with model3D_aug_-40_00_10.mat
> Using pose model in model3D_aug_-40_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject4_a.jpg with model3D_aug_-55_00_10.mat
> Using pose model in model3D_aug_-55_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject4_a.jpg with model3D_aug_-75_00_10.mat
> Using pose model in model3D_aug_-75_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Yaw value mean:  -9.47109702685
> Looking at file: ./tmp/subject7_a.jpg with model3D_aug_-00_00_10.mat
> Using pose model in model3D_aug_-00_00_10.mat
> Query image shape: (227, 227, 3)
> Looking at file: ./tmp/subject7_a.jpg with model3D_aug_-22_00_10.mat
> Using pose model in model3D_aug_-22_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject7_a.jpg with model3D_aug_-40_00_10.mat
> Using pose model in model3D_aug_-40_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject7_a.jpg with model3D_aug_-55_00_10.mat
> Using pose model in model3D_aug_-55_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject7_a.jpg with model3D_aug_-75_00_10.mat
> Using pose model in model3D_aug_-75_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Yaw value mean:  -25.5160943533
> Looking at file: ./tmp/subject9_a.jpg with model3D_aug_-40_00_10.mat
> Using pose model in model3D_aug_-40_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject9_a.jpg with model3D_aug_-55_00_10.mat
> Using pose model in model3D_aug_-55_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject9_a.jpg with model3D_aug_-75_00_10.mat
> Using pose model in model3D_aug_-75_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Yaw value mean:  32.5320004185
> Looking at file: ./tmp/subject5_a.jpg with model3D_aug_-40_00_10.mat
> Using pose model in model3D_aug_-40_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject5_a.jpg with model3D_aug_-55_00_10.mat
> Using pose model in model3D_aug_-55_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject5_a.jpg with model3D_aug_-75_00_10.mat
> Using pose model in model3D_aug_-75_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Yaw value mean:  7.65499397088
> Looking at file: ./tmp/subject1_a.jpg with model3D_aug_-00_00_10.mat
> Using pose model in model3D_aug_-00_00_10.mat
> Query image shape: (227, 227, 3)
> Looking at file: ./tmp/subject1_a.jpg with model3D_aug_-22_00_10.mat
> Using pose model in model3D_aug_-22_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject1_a.jpg with model3D_aug_-40_00_10.mat
> Using pose model in model3D_aug_-40_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject1_a.jpg with model3D_aug_-55_00_10.mat
> Using pose model in model3D_aug_-55_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject1_a.jpg with model3D_aug_-75_00_10.mat
> Using pose model in model3D_aug_-75_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Yaw value mean:  31.204200148
> Looking at file: ./tmp/subject2_a.jpg with model3D_aug_-40_00_10.mat
> Using pose model in model3D_aug_-40_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject2_a.jpg with model3D_aug_-55_00_10.mat
> Using pose model in model3D_aug_-55_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym
> Looking at file: ./tmp/subject2_a.jpg with model3D_aug_-75_00_10.mat
> Using pose model in model3D_aug_-75_00_10.mat
> Query image shape: (227, 227, 3)
> skipping sym

**Comment by st100945** [comment]
I have the same issue, how can i get the result like:
"Model restored.
Predicted pose for: subject10_a
[ 8.27930197e-02 1.95288494e-01 1.03690195e+00 -1.98086071e+01
8.39025688e+00 3.26982227e+03]
Predicted pose for: subject10_a_flip
[ 1.37187794e-01 -1.48106769e-01 -1.06753802e+00 2.50120773e+01
4.28642845e+00 3.29182764e+03]
and so on..."

when running main_fpn.py I currently get:
"Model restored.
Predicted pose for: subject10_a
Predicted pose for: subject10_a_flip
Predicted pose for: subject3_a
Predicted pose for: subject3_a_flip
and so on..."
