### ISSUE TITLE
Question about landmark detection

### ISSUE THREAD

**Issue by nicenice97** [fengju514/Face-Pose-Net#17]
Hello, I'd like to know how to display photos marked with feature points.
Best regards.

**Comment by fengju514** [comment]
Our code does not provide the landmarks directly but 6 DoF 3D head poses and rendered images in specific poses.
To get landmarks, you need the marked 3D landmarks and apply the projection matrix estimated by our code.

**Comment by nicenice97** [comment]
Thank you. In your paper, you said the training set is produced by running on existing landmark detector on VGG dataset. I want to know if there is a step to extract feature points?
Is the landmarks extracted but not displayed, or is the landmark detection not used at all?
