### ISSUE TITLE
how can I sign the render yaw angel?

### ISSUE THREAD

**Issue by HaoLiuHust** [fengju514/Face-Pose-Net#27]
I want to render the input to a particular angle, is it possible?

**Comment by iacopomasi** [comment]
you might need to add the new views that you want with [this](https://github.com/iacopomasi/face_specific_augm/tree/master/render_mat_demo)

**Comment by HaoLiuHust** [comment]
thanks very much,　wonderful work

**Comment by HaoLiuHust** [comment]
@iacopomasi I have sent an email to you, could you send me the 3D models that required to create new views?
