### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by fuhuacy** [fengju514/Face-Pose-Net#28]
Hello,
Please help me to solve this problem, thanks very much!

Traceback (most recent call last):
  File "/home/zheng/Face-Pose-Net/main_fpn.py", line 23, in <module>
    input_file = str(sys.argv[1]) #'input.csv'
IndexError: list index out of range

**Comment by fuhuacy** [comment]
/usr/bin/python2.7 /home/zheng/Face-Pose-Net/main_fpn.py
> Preloading all the models for efficiency
> Loading pose model in model3D_aug_-00_00_01.mat
> Loading pose model in model3D_aug_-00_00_02.mat
> Loading pose model in model3D_aug_-00_00_03.mat
> Loading pose model in model3D_aug_-00_00_04.mat
> Loading pose model in model3D_aug_-00_00_05.mat
> Loading pose model in model3D_aug_-00_00_06.mat
> Loading pose model in model3D_aug_-00_00_07.mat
> Loading pose model in model3D_aug_-00_00_08.mat
> Loading pose model in model3D_aug_-00_00_09.mat
> Loading pose model in model3D_aug_-00_00_10.mat
> Loading pose model in model3D_aug_-22_00_01.mat
> Loading pose model in model3D_aug_-22_00_02.mat
> Loading pose model in model3D_aug_-22_00_03.mat
> Loading pose model in model3D_aug_-22_00_04.mat
> Loading pose model in model3D_aug_-22_00_05.mat
> Loading pose model in model3D_aug_-22_00_06.mat
> Loading pose model in model3D_aug_-22_00_07.mat
> Loading pose model in model3D_aug_-22_00_08.mat
> Loading pose model in model3D_aug_-22_00_09.mat
> Loading pose model in model3D_aug_-22_00_10.mat
> Loading pose model in model3D_aug_-40_00_01.mat
> Loading pose model in model3D_aug_-40_00_02.mat
> Loading pose model in model3D_aug_-40_00_03.mat
> Loading pose model in model3D_aug_-40_00_04.mat
> Loading pose model in model3D_aug_-40_00_05.mat
> Loading pose model in model3D_aug_-40_00_06.mat
> Loading pose model in model3D_aug_-40_00_07.mat
> Loading pose model in model3D_aug_-40_00_08.mat
> Loading pose model in model3D_aug_-40_00_09.mat
> Loading pose model in model3D_aug_-40_00_10.mat
> Loading pose model in model3D_aug_-55_00_01.mat
> Loading pose model in model3D_aug_-55_00_02.mat
> Loading pose model in model3D_aug_-55_00_03.mat
> Loading pose model in model3D_aug_-55_00_04.mat
> Loading pose model in model3D_aug_-55_00_05.mat
> Loading pose model in model3D_aug_-55_00_06.mat
> Loading pose model in model3D_aug_-55_00_07.mat
> Loading pose model in model3D_aug_-55_00_08.mat
> Loading pose model in model3D_aug_-55_00_09.mat
> Loading pose model in model3D_aug_-55_00_10.mat
> Loading pose model in model3D_aug_-75_00_01.mat
> Loading pose model in model3D_aug_-75_00_02.mat
> Loading pose model in model3D_aug_-75_00_03.mat
> Loading pose model in model3D_aug_-75_00_04.mat
> Loading pose model in model3D_aug_-75_00_05.mat
> Loading pose model in model3D_aug_-75_00_06.mat
> Loading pose model in model3D_aug_-75_00_07.mat
> Loading pose model in model3D_aug_-75_00_08.mat
> Loading pose model in model3D_aug_-75_00_09.mat
> Loading pose model in model3D_aug_-75_00_10.mat
> loading getRts
> make dir
Traceback (most recent call last):
  File "/home/zheng/Face-Pose-Net/main_fpn.py", line 23, in <module>
    input_file = str(sys.argv[1]) #'input.csv'
IndexError: list index out of range

Process finished with exit code 1

**Comment by fengju514** [comment]
You should feed in the input file (Please see input.csv for the correct format) as you run main_fpn.py

**Comment by FUHUACANGYUE** [comment]
@fengju514  Thank you! I got it.
can you explain what is the meaning of FACE_X, FACE_y, FACE_WIDTH, FACE_HEIGHT? And how to get FACE_X, FACE_y, FACE_WIDTH, FACE_HEIGHT?  Why should get face landmark?

**Comment by iacopomasi** [comment]
@FUHUACANGYUE It is very simple: it is the output from a face detector. Those are coordinates of a face bounding box (a rectangle). So you can use your own favorite face detector to produce that. There is not face landmark involved.

**Comment by fuhuacy** [comment]
@iacopomasi  Thanks for your reply!
I know those are coordinates of a face bounding box (a rectangle),and I guess FACE_WIDTH, FACE_HEIGHT are respectively the width and height of the bounding fox, but I do not figure out what is the FACE_X, FACE_y?

**Comment by iacopomasi** [comment]
top-left point of the bounding box.

**Comment by fuhuacy** [comment]
https://github.com/fengju514/Face-Pose-Net/issues/6

**Comment by fuhuacy** [comment]
Thanks for your reply! Can you solve this problem in https://github.com/fengju514/Face-Pose-Net/issues/6
I use my own image and detector tool, but the result is not well. I do not know how to do to solve it? Should the image be rescaled to 227 227 pixel?

**Comment by fuhuacy** [comment]
@iacopomasi 
Thanks for your reply! Can you solve this problem in #6
I use my own image and detector tool, but the result is not well. I do not know how to do to solve it? Should the image be rescaled to 227 227 pixel?
