### ISSUE TITLE
Frontalize face

### ISSUE THREAD

**Issue by ileniTudor** [fengju514/Face-Pose-Net#31]
First of all, @fengju514  thank you for sharing this work. I'm a little bit confuse about the using of the rendering models of kind "model3D_aug_-.._.._..mat". By reading the code I saw that the yaw angle is used for rendering. My question is: if I want to frontalize the face (bring yaw, pitch, roll angle to 0) it is enough to run the demo code (from face_renderer) with the following model "models3d_new/model3D_aug_-00_00_01.mat"?
Thank you

**Comment by iacopomasi** [comment]
Yes, in general, what you said should work, keep in mind that the frontalization works for near frontal faces only.

I hope this helps.
