### ISSUE TITLE
ValueError: Too Many Values to Unpack

### ISSUE THREAD

**Issue by st100945** [fengju514/Face-Pose-Net#32]
when running "python main-fpn.py input.csv" I receive the "ValueError: too many values to unpack" when loading the pose model in model3D_aug_-00_00_01.mat, any idea what I'm doing wrong here?
I get the same error when trying to run "python main_fpn.py subject1_a,images/input1.jpg,108.2642,119.6774,170,179"

error is in line 10 of main_fpn.py
line 34 in renderer_fpn.py when loading the models

**Comment by iacopomasi** [comment]
You can check this issue: https://github.com/iacopomasi/face_specific_augm/issues/12
It is related to the fact you are using OpenCV 3 instead version 2.x is expected.
