### ISSUE TITLE
I make a better one [https://github.com/WIKI2020/FacePose_pytorch]

### ISSUE THREAD

**Issue by WIKI2020** [fengju514/Face-Pose-Net#47]
I make a better one [https://github.com/WIKI2020/FacePose_pytorch]

**Comment by TalHassner** [comment]
Nice work, @WIKI2020  , but  from what I can tell, unlike our FacePoseNet, you're only regressing 3DoF: the three rotation angles. You need all six degrees for it to be the head pose (for it to be usable for face alignment, new view synthesis, etc.) With only the three angles, the applications your implementation can be used for are somewhat limited.  Still, good job!
