### ISSUE TITLE
Is training label available？

### ISSUE THREAD

**Issue by szc1523** [fengju514/Face-Pose-Net#5]
Hi, congratulations on your great work! I am wondering if you have the plan to release your training label (the generated 6Dofs from landmark).

**Comment by iacopomasi** [comment]
Hi @szc1523 ,
thank you for your interest. We are not planning to make the training data available yet but the way we produced the data should be pretty easy to re-implement.  What you need is:

1. a landmark detector
2. random sampling parameters for similarity alignment.
3. map back the previous pose on the original, easy image to the perturbed image to get new challenging training data.

I hope this helps.
