### ISSUE TITLE
Pose problem

### ISSUE THREAD

**Issue by qmj123** [fengju514/Face-Pose-Net#6]
Hello!
I have a question than how do I get the value of pitch and roll ?
Could you give me some advise ?
Thanks a lot.

**Comment by RomainSabathe** [comment]
Hey,
In `get_Rts.py`, on line 105ish you obtain `predRts`. The pose is given by:
pitch: `pred_Rets[0][0]`,
yaw: `pred_Rets[0][1]`,
roll: `pred_Rets[0][2]`.

**Comment by qmj123** [comment]
I am very excited to see your reply.
Thank you very very much!

**Comment by qmj123** [comment]
@RomainSabathe Hi!
In camera_calibration.py, the get_yaw(rmat) means the value of yaw of the original image.
Is that right?
Could you help me ?
Tkank you !

**Comment by RomainSabathe** [comment]
Hey @qmj123, honnestly I'm not too familiar with this project. It seems to be a yaw indeed but it seems to me it's rather related to the 3d model they apply on the face. I might be wrong.
(it's confusing me as well).

**Comment by qmj123** [comment]
Hi!@RomainSabathe 
ok! I am very excited to see your reply.
Thank you very much!

**Comment by qmj123** [comment]
Hi! @RomainSabathe 
I have another question that what is the role of these  parameters in input.csv and how to get these parameters ?
I think the effect of these parameters is to cut and flip the image. Is that right?
What method should I use to get these parameters?
Could you help me ?
Tkank you !

**Comment by RomainSabathe** [comment]
Hey @qmj123, the parameters in input.csv are the bounding box of the face in the image. It's encoded by 4 values: x and y coordinates of the top left corner + the width and height of the box.
There are plenty of tools available online to find those values. The most famous and straightforward ones are the **dlib** face detector and the one packed with OpenCV (Viola-Jones method).

**Comment by qmj123** [comment]
@RomainSabathe 
Hello! 
Thank you very much for your help.
Thank you for your patience.

**Comment by qmj123** [comment]
@RomainSabathe 
Hello!
I have a problem that how to get real time the value of pitch and roll in the video and what method to use?
Thank you very much!

**Comment by RomainSabathe** [comment]
Hey. What do you mean real time? I guess it's do-able but the code is not structured to do that. It's designed to process a sequence of frames, already stored somewhere. 
So there's no direct solution to your problem. You'll have to dig and modify large parts of the code, I'm afraid.

**Comment by qmj123** [comment]
@RomainSabathe 
Hello,I mean that when camera opens,it can estimation the head pose and get the value of per frame.
If I do that,I will need to modify the code.
ok! I see.
Thank you for your reply.

**Comment by fuhuacy** [comment]
![subject1_a](https://user-images.githubusercontent.com/42868077/45273712-e45ed080-b481-11e8-9757-85c85668dbe0.jpg)
![subject1_a_flip](https://user-images.githubusercontent.com/42868077/45273713-e4f76700-b481-11e8-91f0-ab4fcb2366a6.jpg)

**Comment by fuhuacy** [comment]
@RomainSabathe @iacopomasi @qmj123   I choose other method to detect face bounding box, but the result above is not well.  The photos above are stored in tmp folder.

**Comment by fuhuacy** [comment]
The face_x face_y width height of input1.jpg are:
subject1_a | images/input1.jpg | 108.2642 | 119.6774 | 170 | 179 
the coordinates I use are
subject1_a | images/input1.jpg | 79 | 334 | 228 | 308

**Comment by fuhuacy** [comment]
![1 16 ac nb usus h0 ci](https://user-images.githubusercontent.com/42868077/45274009-57b51200-b483-11e8-87e0-166cd178ac00.png)
![ct 3jawex kzue 4_acq v](https://user-images.githubusercontent.com/42868077/45274010-57b51200-b483-11e8-8341-707818a9d208.png)
 This is the tool i choose to detect face bounding box.

**Comment by fuhuacy** [comment]
The problem is I can not get complete picture of  subject1_a.jpg and subject1_a_flip.jpg in tmp folder, I want to know how to solve it. Thanks!
