### ISSUE TITLE
Unit of pose

### ISSUE THREAD

**Issue by RomainSabathe** [fengju514/Face-Pose-Net#7]
Hi, thank you for your great work. 

In all the tests I've done, I never reached a yaw greater than 1 (or -1 in the negative) even though the subject was clearly viewed from profile. Hence I'm wondering what the unit of pose is.

Is it rad? Or has it been squeezed to [-1, 1]?

Thanks

**Comment by fengju514** [comment]
The unit of yaw is radian. The predicted yaw angle range may depend on the training yaw angle distribution and the quality of generated ground truth labels. It would be poor sometimes in the near profile cases.
