### ISSUE TITLE
How to create other precomputed pose model?

### ISSUE THREAD

**Issue by hjy1312** [fengju514/Face-Pose-Net#9]
Hi,
@iacopomasi 
I am a new beginner. I have checked the code from the example usage of [https://www.openu.ac.il/home/hassner/projects/poses/](url), but i don't know how to get the reference textured 3D model and how to set the parameters distance, elevation  and azimuth.
Could you please tell me how to do?
Thanks.

**Comment by iacopomasi** [comment]
Hi @hjy1312 ,
You need to have a generic 3D model _without the texture_ to generate the unprojected matrix following that code you mentioned. The code you mentioned provide a call to change the viewpoint (elevation, azimuth or pan, tilt) etc.

We will probably release our script soon for generating the models.

**Comment by hjy1312** [comment]
Additionally,
@iacopomasi 
I find the model should include parameters such as ref_U,out_A,indbad,face mask,etc, but the code doesn't refer to the generation of face mask. I am wonderring how to generate it.

**Comment by iacopomasi** [comment]
The code I pointed you is a general code to achieve what you need. It does not provide code ready to use with the renderer. Anyway, I use that framework to produce the 3D rendered views.

I will see what I can do to expedite the release of that script.

**Comment by hjy1312** [comment]
Okay,thank you very much.
